export const styles = {
  root: {
    "--bg": "#0d0f14",
    "--surface": "#161921",
    "--border": "#252934",
    "--accent": "#4f8ef7",
    "--accent-dim": "#1e2d4d",
    "--text": "#e8eaf0",
    "--text-secondary": "#7a8099",
    "--muted": "#2d3040",
    "--success": "#2eb87a",
    "--danger": "#e05c5c",
    minHeight: "100vh",
    background: "var(--bg)",
    color: "var(--text)",
    fontFamily: "'Manrope', 'Segoe UI', sans-serif",
    fontSize: 14,
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 32px",
    borderBottom: "1px solid var(--border)",
    background: "var(--surface)",
    position: "sticky",
    top: 0,
    zIndex: 10,
  },
  headerLeft: { display: "flex", alignItems: "center", gap: 12 },
  headerRight: { display: "flex", alignItems: "center", gap: 16 },
  headerTitle: { fontWeight: 700, fontSize: 16, letterSpacing: "0.02em" },
  logoMark: {
    width: 28,
    height: 28,
    borderRadius: 6,
    background: "linear-gradient(135deg, #4f8ef7, #9b6df7)",
    flexShrink: 0,
  },
  codesCount: { color: "var(--text-secondary)", fontSize: 13 },

  toolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "20px 32px",
  },

  tableWrapper: {
    padding: "0 32px 40px",
    overflowX: "auto",
  },
  table: { width: "100%", borderCollapse: "collapse" },
  th: {
    textAlign: "left",
    padding: "10px 14px",
    color: "var(--text-secondary)",
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    borderBottom: "1px solid var(--border)",
    whiteSpace: "nowrap",
  },
  tr: {
    borderBottom: "1px solid var(--border)",
    transition: "background 0.15s",
  },
  td: { padding: "13px 14px", verticalAlign: "middle" },

  codeChip: {
    background: "var(--accent-dim)",
    color: "var(--accent)",
    borderRadius: 4,
    padding: "3px 8px",
    fontWeight: 700,
    fontSize: 12,
    letterSpacing: "0.05em",
  },
  badge: {
    display: "inline-block",
    borderRadius: 99,
    padding: "3px 10px",
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.04em",
  },
  badgeActive: { background: "rgba(46,184,122,0.15)", color: "var(--success)" },
  badgeInactive: { background: "rgba(224,92,92,0.16)", color: "var(--danger)" },
  userCount: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 28,
    height: 24,
    borderRadius: 4,
    background: "var(--muted)",
    color: "var(--text)",
    fontWeight: 600,
    fontSize: 13,
    padding: "0 8px",
  },
  actions: { display: "flex", gap: 6 },
  btnAction: {
    background: "none",
    border: "1px solid var(--border)",
    borderRadius: 5,
    color: "var(--text-secondary)",
    padding: "4px 10px",
    cursor: "pointer",
    fontSize: 12,
    fontFamily: "inherit",
    transition: "color 0.15s, border-color 0.15s",
  },

  emptyState: {
    textAlign: "center",
    padding: "60px 0",
    color: "var(--text-secondary)",
  },

  form: { display: "flex", flexDirection: "column", gap: 16 },
  label: { display: "flex", flexDirection: "column", gap: 6, fontSize: 13, color: "var(--text-secondary)" },
  input: {
    background: "var(--bg)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    color: "var(--text)",
    fontFamily: "inherit",
    fontSize: 14,
    padding: "9px 12px",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
    transition: "border-color 0.15s",
  },
  formActions: { display: "flex", justifyContent: "flex-end", gap: 10, marginTop: 4 },
  errorMsg: { color: "var(--danger)", fontSize: 13, margin: 0 },

  toggle: {
    width: 38,
    height: 22,
    borderRadius: 99,
    cursor: "pointer",
    position: "relative",
    flexShrink: 0,
    transition: "background 0.2s",
  },
  toggleThumb: {
    position: "absolute",
    top: 2,
    width: 18,
    height: 18,
    borderRadius: "50%",
    background: "#fff",
    transition: "transform 0.2s",
  },

  btnPrimary: {
    background: "var(--accent)",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    padding: "9px 18px",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 13,
    fontWeight: 600,
    whiteSpace: "nowrap",
    transition: "opacity 0.15s",
  },
  btnSecondary: {
    background: "none",
    border: "1px solid var(--border)",
    borderRadius: 6,
    color: "var(--text-secondary)",
    padding: "9px 18px",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 13,
    transition: "color 0.15s",
  },
  btnGhost: {
    background: "none",
    border: "none",
    color: "var(--text-secondary)",
    cursor: "pointer",
    fontSize: 13,
    fontFamily: "inherit",
    padding: "4px 8px",
  },

  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.6)",
    backdropFilter: "blur(4px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
  },
  modal: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 10,
    padding: 28,
    width: "100%",
    maxWidth: 440,
    boxShadow: "0 24px 60px rgba(0,0,0,0.5)",
  },
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  modalTitle: { fontWeight: 700, fontSize: 16 },
  closeBtn: {
    background: "none",
    border: "none",
    color: "var(--text-secondary)",
    cursor: "pointer",
    fontSize: 16,
    padding: 4,
    lineHeight: 1,
    fontFamily: "inherit",
  },

  loginWrapper: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "var(--bg)",
  },
  loginCard: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 12,
    padding: 36,
    width: "100%",
    maxWidth: 380,
    boxShadow: "0 20px 60px rgba(0,0,0,0.4)",
  },
  loginLogo: { display: "flex", alignItems: "center", gap: 12, marginBottom: 6 },
  logoText: { fontWeight: 700, fontSize: 17 },
  loginSub: { color: "var(--text-secondary)", margin: "0 0 24px", fontSize: 13 },

  toastContainer: {
    position: "fixed",
    bottom: 24,
    right: 24,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    zIndex: 200,
  },
  toast: {
    padding: "12px 18px",
    borderRadius: 7,
    fontSize: 13,
    fontWeight: 600,
    boxShadow: "0 6px 20px rgba(0,0,0,0.35)",
    animation: "fadeIn 0.2s ease",
  },
  toastSuccess: { background: "#1a3a2a", color: "var(--success)", border: "1px solid rgba(46,184,122,0.3)" },
  toastError: { background: "#3a1a1a", color: "var(--danger)", border: "1px solid rgba(224,92,92,0.3)" },
};
