services:
  fastify_db:
    image: postgres:15
    container_name: fastify_db
    restart: always
    environment:
      POSTGRES_USER: awesomeuser
      POSTGRES_PASSWORD: secretpw
      POSTGRES_DB: aikidev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_fastify:/var/lib/postgresql/data

volumes:
  postgres_data_fastify: